version: '3'

services:
    entrypoint:
        build:
            context: ./entrypoint
        ports:
            - '8080:80'
        depends_on:
            - app
            - api
            - forum-staging

    app:
        build:
            context: ./app

    api:
        build:
            context: ./api/prod

    subforum-api:
        build:
            context: ./subforum-api
            dockerfile: prod.Dockerfile

    discord-bot-api:
        build:
            context: ./discord-bot-api
            dockerfile: prod.Dockerfile
        environment:
            - BOT_TOKEN=${DISCORD_BOT_TOKEN}

    forum-db:
        image: 'docker.io/bitnami/mariadb:10.3-debian-10'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=bn_phpbb
            - MARIADB_DATABASE=bitnami_phpbb
            - BITNAMI_DEBUG=true
        volumes:
            - '/home/circleci/docker/forum-db-persistance:/bitnami/mariadb'
        expose:
            - 3306
        restart: unless-stopped
    forum-staging:
        build:
            context: ./forum-staging
        environment:
            - PHPBB_DATABASE_HOST=forum-db
            - PHPBB_DATABASE_PORT_NUMBER=3306
            - PHPBB_DATABASE_USER=bn_phpbb
            - PHPBB_DATABASE_NAME=bitnami_phpbb
            - ALLOW_EMPTY_PASSWORD=yes
            - SHINOBI_WAR_FAIRY_DB_PREFIX=phpbb
        depends_on:
            - forum-db
        volumes:
            - '/home/circleci/docker/forum-staging-persistance:/opt/bitnami/phpbb'
