version: '3'

services:
    entrypoint:
        build:
            context: ./entrypoint
        ports:
            - '80:80'
        depends_on:
            - app
            - api
            - forum-staging

    app:
        build:
            context: ./app
        volumes:
            - './app:/usr/share/nginx/html'

    api:
        build:
            context: ./api
            dockerfile: dev.Dockerfile
        volumes:
            - './api:/home/node/app'

    subforum-api:
        build:
            context: ./subforum-api
            dockerfile: dev.Dockerfile
        volumes:
            - './subforum-api:/home/node/app'

    discord-bot-api:
        build:
            context: ./discord-bot-api
            dockerfile: dev.Dockerfile
        volumes:
            - './discord-bot-api:/home/node/app'

    forum-db:
        image: 'docker.io/bitnami/mariadb:10.3-debian-10'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=bn_phpbb
            - MARIADB_DATABASE=bitnami_phpbb
            - BITNAMI_DEBUG=true
        volumes:
            - '/persistance/forum-db:/bitnami/mariadb'
        expose:
            - 3306
        restart: always
    forum-staging:
        build:
            context: ./forum-staging
        environment:
            - PHPBB_DATABASE_HOST=forum-db
            - PHPBB_DATABASE_PORT_NUMBER=3306
            - PHPBB_DATABASE_USER=bn_phpbb
            - PHPBB_DATABASE_NAME=bitnami_phpbb
            - ALLOW_EMPTY_PASSWORD=yes
            - SHINOBI_WAR_FAIRY_DB_PREFIX=phpbb
        volumes:
            - './forum:/opt/bitnami/phpbb'
            - './forum-staging/mods:/opt/bitnami/phpbb/store/mods'
        depends_on:
            - forum-db
