version: '3'

services:

  entrypoint: 
    build:
      context: ./entrypoint
    ports:
      - "80:80"
    depends_on:
      - app
      - api

  app:
    build:
      context: ./app

  api:
    build:
      context: ./api