version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
       - image: circleci/node:7.10
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $PRODUSER@$PROD 'cd shinobi-war-fairy && ./deploy.sh'
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "this is the test job"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - main